language: php
php:
- 7.2
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
- mkdir -p ./build/coverage
- wget https://github.com/infection/infection/releases/download/0.13.0/infection.phar
- wget https://github.com/infection/infection/releases/download/0.13.0/infection.phar.asc
- gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
- gpg --with-fingerprint --verify infection.phar.asc infection.phar
- chmod +x infection.phar
script:
- composer travis
- "./infection.phar --min-msi=48 --threads=4"
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
env:
  global:
    secure: b7WbZ1aquZIyGxq0Zoy6ujUZFp056UJojLrrCjOlNjzJ8FI7EU5JGl7jhm1G6V5r4sgqXXVmOIZAsLLCq/UccDZWXo9qMtYT30uiKF3ATZ/0kBb2juIbNreUwDcwfEZ0q4dD7Eg9g118FwyrnJi16TVedLEAd8/FPumrcye12AOfCF34NX9yVrYseEPrqThfqlxvfn40g7iVlKwScpgP6dZD8+JoMMvZNBObgMeRmYe5Qjvh8DQIt1e9XNJmtIA5oFY6FEGXgT/s5zN2/cOHy8ORhn8y9CFlYjoRO2sH+SwMH5tmzMEzBIsiaYAU7viBGntIFKZan5qaIeu9zDct++8puzPfPgLrsGmmNp5ddsb7v9UxlLszoqf1L38PpczE213u7FIFFB3Ww98Xr/Lv3xVdFqadA7YcE6hzFKVBNQqWXiAxNu0u+SDHZOIXg4/x3A6StngWh7DTpmXKy9YQA7jMEwvro0nCvDMr9ESeT3PUA+BdFnO3YLG/YccASq21equLoWqgPAWYtNuspeHFcmZEZlfYychykDeEeGRC9kAUGfYS0cSrH/fgdJ9kyY+FChhcQXWoftYW1lV2C2UBpfBhLvnI/2VpZGug7jqm36KHfeRM7tZ13uYGwbtJpEY0BSdkZ8Q+WMzYR3vJ6jsKaqw10M10omDs34CxgLGlruc=
