language: php
php:
- 7.2
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
- mkdir -p ./build/coverage
script:
- composer travis
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
env:
  global:
    secure: Vb8Rjc02gvTzijyxBb/IqyDw3T4AYUOkFO6gzEzZ/IcIDemmnNo6fmmu8Z2LIcuxWBZBhd39kyJCVsfurllV8V0rFBlT/GeV6EAYWSD3gW6o1qZkedYBhcSy5GmQ6WE+Ma0oTUaXlDeXpPi5Xjumo5ogo37NX6KAcl6T/Yk8JcNFNPXLNdZgOjRFZDNDciX/GaSq8K3jTIwVamM/0F4MqR8/uDH2eSh6EiYjZnrD1O5GTHqEFpui6sI5MbC3bcauE0LMj/c3Hv2IMQ6dyod0J28pArIp59VC26B4lOXpGl7IkeKg12pJb1JOSwzMpS49hbJ9H170t7ctyOIu2kjrFV6k4upFxjKe8nCy64jcLJ2FJI5PAllFNxShEhDab9IXioVzGBOLIhc8Aj18KJClYmmxmF+x99PToVT7VYFwWqdg5LcMz272tHImS787D233kSzEMve5+CRJn6sR0vOt8fIzCxpoM7yG0L068DIDYHWhASf1PUWJ0SXutPb5+TLtenzzm11h0/S2wi2I/lhFzWkiKlWr9/yJMjfdtNwm6fvwXPnWpso7z2xnknpVQlEav6WMFCEHKBVHtzOq6AEwpNYVwUEk01pmYYGjGvevcSsCRi68MNFpOd92wfw4IuHpb26KpeNW7aGeUCGEsJ7CXueZA7A9Cj5kvT2HsWFuPb8=
