language: php
php:
- 7.2
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
- mkdir -p ./build/coverage
- wget https://github.com/infection/infection/releases/download/0.13.0/infection.phar
- wget https://github.com/infection/infection/releases/download/0.13.0/infection.phar.asc
- gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 493B4AA0
- gpg --with-fingerprint --verify infection.phar.asc infection.phar
- chmod +x infection.phar
script:
- composer travis
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
env:
  global:
    secure: lZoHD6hYQaC/yvOmt8QlmPYVUIlzZpWfKRxNH+K93egenBgHGdR0WIgwFEzYSkvhdFefERqMUgf5XBRIkrYZPSR6TYCLE+d0K3rOA/AwoZcYpGo7vqroC0jgBkbyb5QA/gvQLrBwtfVIvuH1RyVWtXTfDEJ8P2q26u3iMkd2yf53sVSz7Tsy32TbaSvdifZU/tzCfulqWRvEBGeQ9BOyN6PZ0cY/40ZVRrFKNxo4abm5LVNLXh7Gehi0+/r+66AHMTlRrII6rRqJ+grRbeV8y2YPkCN+pqSW9PHSuhxMihX0YbuL0rWJ3E5j739HNC4tAWSvJmo+zMkLlVcRPWP6G0X4J0VhY8/EFNzhgaSjVRIQ3onDVG7Wxanh8EseMLj8f1SHd7rqYxmx8IOmKUpjvNzO4Z84w97vtsW5Q90GbswyujuAV46nBXEAV9WukeMyerT+NTTmaRGDHDBH17inLwnOag+DkwFPnSI6M+FRXN/Mu52Nv6qzCMBxaY0qh3GmbMFlu2v6jobeME5qpb4XCOSI4RTD9xEd0y9kPjzvJkAiI0y8Ay6CQXdMwYoSGn3RjQG0glmAd4lYY+R5om/Fo5ddjISbGlIjPB53Ds0y0NqRpLzuJ90w1l+rJ5FDp6GEPUOsAdo2famBe3nelEVnOeqWZNOpXDoMIGp4aj9RtsI=
