language: php
php:
- 7.2
before_script:
- composer self-update
- composer install --prefer-source --no-interaction
- mkdir -p ./build/coverage
script:
- composer travis
after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover ./build/coverage/clover.xml
matrix:
  fast_finish: true
notifications:
  on_success: never
  on_failure: always
env:
  global:
  - secure: kVzgkCGL1fa8ssbEZrabc0g5I5linpzoSCfCIQ+vSqcZ/HBeAon8s9ePMeC75WcJ6v3pm+QD5Yqb0MIGB8T3kHGX16/l+/aOH8p0FCiwSOMR7hgFkcoQA0R+UTtt7cHWcRUUfsLMBkkmec3sdieZW58406ezCIktW/cLXMaGgrSRqvt4XG1BaI03B6tFEEPcXkbJ0ZlsYzRh6Nugqv+sSZ4thpaDnAa0O9uIsgFhV9UvLUdks3MznSa090R0j2c3F154S0XU4cVUU+DYbwBiTmnl1Mr00YMT8/Vmt3NVj141jPXAIBrYIzsTKi3kbvu8AUCqOu9KrgJc4EgdwxiCt+GEVRHRHpFPaOo6ZY5MqDj78aiyvs+Fp19O7vz1tyGrzyKceuF9LJ2xHwbzTm0Q9ySRcvdnVYVwB3MfsM5L0GDWI47t+4ogxsi5TweJ6C5AB5otBzG+359tFY/vgJAEsuKNMIj9V3bOZci5bc9Yl/et5hnDLXLbz5wjasLZANXOblyPlwKyAzfiObEW8d1QDGCxxp5B6YtRLq04HT7Y7fq71AQinCv/FjDbLQZVlDwahqVADGUsMBqSDFVT5NO1ATRdy1m/8MCkYWrdOqUhg6bSJdEwbDocTVfWXqAHhKQuhIWqU8P3EsGsdKG9Eh8CRR3m37rkbvudDaFJmduMjbA=
